### ISSUE TITLE
Bug: File Hashing

### ISSUE THREAD

**Issue by daminals** [sbu-416-24sp/orcanet-rust#10]
The proto file for the market/peer communication does not include a place for an array of hashes, so that the consumer is able to verify each chunk after a purchase, rather than waiting until the end of a file has been reached to check the entire file

**Comment by reaovyd** [comment]
#6 might be relevant here: think the prof wants it as a single process now? So, the protobuf file only essentially serves as the definition for gRPC communication between the market and the peer unless you mean just use it as a specification for now. We'll look into integrating this into our implementation though.

**Comment by daminals** [comment]
Doesn't need to be a proto file, mostly just relevant for pr #9 to define a way for the consumer to check they aren't getting scammed. Any communication method should be fine.
