### ISSUE TITLE
Implement the `register_file` method

### ISSUE THREAD

**Issue by reaovyd** [sbu-416-24sp/orcanet-rust#17]
# Feature Request
Implement the `register_file` method

Depends on #13 

## Please Describe The Problem To Be Solved

The problem we want to solve is that a peer needs to be able to register a file on the market that they want to sell. A peer must provide to our library the following info to match the `User` as specified in the [protobuf spec](https://gist.github.com/snitski/83a603e926c973862370cba1d3cb1e87):

1. A username to identify the peer
2. An IP address
3. A port
4. A price per chunk for the file

Our library MUST provide the `peer_id`.

Furthermore, a user must provide what's inside the `FileInfo` type specified in the protobuf when registering a file as well. We MUST have some kind of argument that accepts fields related to that and so a peer node implementer MUST pass in a filehash, file chunks, size, and name as well. We SHOULD define some kind of  concrete type for allowing that behavior.

A `Response` must be returned to the user. This will tell the user if the file has been successfully registered or not. A peer node implementer should handle the error accordingly.

**Comment by xiej2520** [comment]
The interface for `register_file` should be

```rust
pub async fn register_file(
    &mut self,
    user: User,
    file_info_hash: FileInfoHash,
    file_info: FileInfo,
) -> Result<()>
```
at least for the `MarketClient` we currently have. `FileInfo` needs to be passed to initialize the empty key-value pair on first insert. We will ignore the case where multiple files have the same `FileInfoHash` for the sake of time.

**Comment by xiej2520** [comment]
I don't think either the JS or Go teams are storing FileInfo in the Dht, or following the format in the spec, so we can simply go with this.
